import SwiftUI
import UniformTypeIdentifiers
import SDKViewerApp

struct ProjectWorkspaceView: View {
    @ObservedObject var viewModel: AppViewModel
    @State private var showImporter = false

    var body: some View {
        VStack(spacing: 16) {
            HStack {
                Text(viewModel.currentProject?.metadata.name ?? "")
                    .font(.headline)
                Spacer()
                Button("Import SDK ZIP") { showImporter = true }
                Button("Close") { viewModel.closeProject() }
            }

            if let dump = viewModel.currentProject?.dump {
                HStack(alignment: .top, spacing: 12) {
                    List(dump.packages, selection: $viewModel.selectedPackage) { pkg in
                        VStack(alignment: .leading) {
                            Text(pkg.name).font(.body)
                            Text("\(pkg.types.count) types").font(.caption).foregroundStyle(.secondary)
                        }
                    }
                    .onChange(of: viewModel.selectedPackage) { _, pkg in
                        viewModel.selectedType = pkg?.types.first
                    }

                    VStack(alignment: .leading, spacing: 8) {
                        if let pkg = viewModel.selectedPackage {
                            Text(pkg.name).font(.title3).bold()
                            List(pkg.types, selection: $viewModel.selectedType) { type in
                                Text("\(type.kind.rawValue): \(type.name)")
                            }
                        } else {
                            Text("Select a package")
                        }
                    }

                    ScrollView {
                        VStack(alignment: .leading, spacing: 8) {
                            if let type = viewModel.selectedType {
                                Text(type.fullName).font(.headline)
                                Text(type.body)
                                    .font(.system(.caption, design: .monospaced))
                                    .textSelection(.enabled)
                            } else {
                                Text("Select a type")
                            }
                        }
                    }
                }

                GroupBox("Pointer Chain Calculator") {
                    VStack(alignment: .leading, spacing: 8) {
                        TextField("Base expression", text: $viewModel.pointerBaseExpression)
                        TextField("Offsets (comma separated, e.g. 0x30, 0x18, 0x8)", text: $viewModel.pointerOffsetsText)
                        TextField("Result type", text: $viewModel.pointerResultType)
                        TextField("Result variable name", text: $viewModel.pointerResultName)
                        Button("Generate C++") { viewModel.generatePointerCode() }
                        Text(viewModel.pointerOutput)
                            .font(.system(.caption, design: .monospaced))
                            .textSelection(.enabled)
                    }
                }
            } else {
                ContentUnavailableView("Import an SDK ZIP", systemImage: "tray.and.arrow.down", description: Text("After project setup, import the ZIP package generated by this repository's iOS dumper."))
            }
        }
        .padding()
        .navigationTitle("Project Workspace")
        .fileImporter(
            isPresented: $showImporter,
            allowedContentTypes: [.zip],
            allowsMultipleSelection: false
        ) { result in
            if case .success(let urls) = result, let url = urls.first {
                viewModel.importDumpArchive(from: url)
            }
        }
        .alert("Error", isPresented: Binding(
            get: { viewModel.errorMessage != nil },
            set: { if !$0 { viewModel.errorMessage = nil } }
        )) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(viewModel.errorMessage ?? "Unknown error")
        }
    }
}
